# Generated by Django 2.1.3 on 2018-11-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20181124_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='borrowed_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
