# Generated by Django 2.1.3 on 2018-11-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20181129_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
