# Generated by Django 2.1.3 on 2018-12-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_composer_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='composer',
            options={'ordering': ('surname', 'first_names', 'suffix')},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('name',)},
        ),
    ]
